//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMedico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MarcarConsulta
    {
        public int IDConsulta { get; set; }
        public int IDPaciente { get; set; }
        public int IDMedico { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Observacoes { get; set; }
    
        public virtual Medicos Medicos { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
